name: Superise BFF (testnet)
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master 

      - name: Upload assets
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./server/*"
          target: "/usr/local/express"
          strip_components: 1
      
      - name: Executing node backend for frontend jobs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            killall node
            cd /usr/local/express
            yarn install
            nohup node index >> express.log 2>&1 &