name: Superise UI
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master 

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1

      - name: Install package
        run: yarn install

      - name: Build project
        run: yarn clean

      - name: Build project
        run: yarn build:testnet

      - name: Upload assets
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./public/*"
          target: "/usr/local/nginx/html"
          strip_components: 1